// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// cr_next_srd
double cr_next_srd(double x_0, double k, double theta, double sigma, double h);
RcppExport SEXP _simJD_cr_next_srd(SEXP x_0SEXP, SEXP kSEXP, SEXP thetaSEXP, SEXP sigmaSEXP, SEXP hSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< double >::type x_0(x_0SEXP);
    Rcpp::traits::input_parameter< double >::type k(kSEXP);
    Rcpp::traits::input_parameter< double >::type theta(thetaSEXP);
    Rcpp::traits::input_parameter< double >::type sigma(sigmaSEXP);
    Rcpp::traits::input_parameter< double >::type h(hSEXP);
    rcpp_result_gen = Rcpp::wrap(cr_next_srd(x_0, k, theta, sigma, h));
    return rcpp_result_gen;
END_RCPP
}
// cr_srd
NumericVector cr_srd(double x_0, double k, double theta, double sigma, int N, double h);
RcppExport SEXP _simJD_cr_srd(SEXP x_0SEXP, SEXP kSEXP, SEXP thetaSEXP, SEXP sigmaSEXP, SEXP NSEXP, SEXP hSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< double >::type x_0(x_0SEXP);
    Rcpp::traits::input_parameter< double >::type k(kSEXP);
    Rcpp::traits::input_parameter< double >::type theta(thetaSEXP);
    Rcpp::traits::input_parameter< double >::type sigma(sigmaSEXP);
    Rcpp::traits::input_parameter< int >::type N(NSEXP);
    Rcpp::traits::input_parameter< double >::type h(hSEXP);
    rcpp_result_gen = Rcpp::wrap(cr_srd(x_0, k, theta, sigma, N, h));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_simJD_cr_next_srd", (DL_FUNC) &_simJD_cr_next_srd, 5},
    {"_simJD_cr_srd", (DL_FUNC) &_simJD_cr_srd, 6},
    {NULL, NULL, 0}
};

RcppExport void R_init_simJD(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
