# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' @rdname r_next_srd
cr_next_srd <- function(x_0, k, theta, sigma, h) {
    .Call(`_simJD_cr_next_srd`, x_0, k, theta, sigma, h)
}

#' @rdname r_srd
cr_srd <- function(x_0, k, theta, sigma, N, h) {
    .Call(`_simJD_cr_srd`, x_0, k, theta, sigma, N, h)
}

